# Generated by Django 3.2.25 on 2024-06-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240612_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='12827828', max_length=20),
            preserve_default=False,
        ),
    ]
